<?php

return [
    'ingest_token_prefix' => 'sgcam_',
    'ingest_token_prefixes' => [
        'camera' => 'sgcam_',
        'rfid_reader' => 'sgrfid_',
        'sensor_device' => 'sgsensor_',
        'gas_gateway' => 'sggas_',
        'edge_device' => 'sgedge_',
    ],
    'snapshot_max_bytes' => 5 * 1024 * 1024,
    'camera_offline_threshold_seconds' => 120,
    'gas_offline_threshold_seconds' => 1200,
    'sensor_offline_threshold_seconds' => 300,
    'rfid_stale_threshold_seconds' => 1800,
    'rfid_stationary_min_seconds' => 1200,
    'correlation_window_seconds' => 30,
    'restricted_zone_types' => ['restricted'],
    'rule_match_to_lsr' => [
        'rfid_unauthorized_zone' => 'LSR-RZ-001',
        'rfid_zone_occupancy' => 'LSR-OC-001',
        'rfid_stationary_tag' => 'LSR-WD-001',
        'gas_lel_high' => 'LSR-GAS-001',
        'gas_o2_out_of_range' => 'LSR-GAS-002',
        'gas_h2s_high' => 'LSR-GAS-003',
        'gas_co_high' => 'LSR-GAS-004',
        'env_co2_high' => 'LSR-ENV-001',
    ],
    'gas_parameter_to_rule_match' => [
        'lel_pct' => 'gas_lel_high',
        'o2_pct' => 'gas_o2_out_of_range',
        'h2s_ppm' => 'gas_h2s_high',
        'co_ppm' => 'gas_co_high',
        'co2_ppm' => 'env_co2_high',
    ],
    'rule_match_to_incident_type' => [
        'fall_detected' => 'fall_detected',
        'person_prone' => 'fall_detected',
        'rfid_stationary_tag' => 'stationary_tag',
        'gas_lel_high' => 'gas',
        'gas_o2_out_of_range' => 'gas',
        'gas_h2s_high' => 'gas',
        'gas_co_high' => 'gas',
        'env_co2_high' => 'gas',
        'ppe_harness' => 'ppe',
    ],
    'correlation_rule_matches' => [
        'fall' => ['fall_detected', 'person_prone'],
        'stationary' => ['rfid_stationary_tag'],
        'harness' => ['ppe_harness', 'working_at_height'],
    ],
    'site_defaults' => [
        'data_residency' => 'on_premise_only',
        'ppe_anonymous_violations' => true,
        'outbound_internet_blocked' => true,
        'iot_expected_devices' => [
            'edge_devices' => 3,
            'rfid_readers' => 8,
            'gas_gateways' => 3,
            'sensor_devices' => 3,
        ],
    ],
    'iot_topology_defaults' => null,
    'udpm_compliance_matrix' => [
        'sections' => 10,
        'automated' => 6,
        'manual' => 2,
        'partial' => 2,
    ],
    'deployment_approval_types' => [
        'cctv_gi' => 'CCTV GI',
        'portable_devices' => 'Portable devices',
        'photography_filming' => 'Photography / filming',
        'cctv_placement_plan' => 'CCTV placement plan',
    ],
    'gas_thresholds' => [
        'lel_pct' => ['low' => 10, 'high' => 20],
        'o2_pct' => ['low' => 19.5, 'high' => 23.5],
        'h2s_ppm' => ['low' => 10, 'high' => 20],
        'co_ppm' => ['low' => 35, 'high' => 200],
        'co2_ppm' => ['warning' => 5000, 'high' => 30000],
    ],
];
